sudo: false
language: go
go:
  - 1.9.x
  - master

matrix:
  include:
    - env: DB=MYSQL8.0
      sudo: required
      dist: trusty
      go: 1.9.x
      services:
        - docker
      before_install:
        - go get golang.org/x/tools/cmd/cover
        - go get -u github.com/golang/dep/cmd/dep
        - dep ensure
        - docker pull mysql:8.0
        - docker run -d -p 127.0.0.1:3307:3306 --name mysqld -v testdata/schema/:/docker-entrypoint-initdb.d/ 
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes mysql:8.0 --innodb_log_file_size=256MB 
          --innodb_buffer_pool_size=512MB --max_allowed_packet=16MB
        - sleep 30
        - .travis/wait_mysql.sh
      before_script:
        - export TEST_DSN="root:@tcp(127.0.0.1:3307)/sakila?parseTime=true"

    - env: DB=MYSQL5.7
      sudo: required
      dist: trusty
      go: 1.9.x
      services:
        - docker
      before_install:
        - go get golang.org/x/tools/cmd/cover
        - go get -u github.com/golang/dep/cmd/dep
        - dep ensure
        - docker pull mysql:5.7
        - docker run -d -p 127.0.0.1:3307:3306 --name mysqld -v testdata/schema/:/docker-entrypoint-initdb.d/ 
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes mysql:5.7 --innodb_log_file_size=256MB 
          --innodb_buffer_pool_size=512MB --max_allowed_packet=16MB
        - sleep 30
        - .travis/wait_mysql.sh
      before_script:
        - export TEST_DSN="root:@tcp(127.0.0.1:3307)/sakila?parseTime=true"

    - env: DB=MYSQL5.6
      sudo: required
      dist: trusty
      go: 1.9.x
      services:
        - docker
      before_install:
        - go get golang.org/x/tools/cmd/cover
        - go get -u github.com/golang/dep/cmd/dep
        - dep ensure
        - docker pull mysql:5.6
        - docker run -d -p 127.0.0.1:3307:3306 --name mysqld -v testdata/schema/:/docker-entrypoint-initdb.d/ 
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes mysql:5.6
          --innodb_log_file_size=256MB --innodb_buffer_pool_size=512MB --max_allowed_packet=16MB
        - sleep 30
        - .travis/wait_mysql.sh
      before_script:
        - export TEST_DSN="root@tcp(127.0.0.1:3307)/sakila?parseTime=true"

script:
  - go test -v -race ./...
