# This is a basic workflow to help you get started with Actions

name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: ${{ GOPATH }}/src/${{ github.repository }}
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reviewdog_flags: -reporter=github-check
